name: Publish to PyPI

on:
  push:
    tags:
     - '*'

jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Setting up Python...
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      
      - name: Installing needed tools...
        run: >-
          python -m
          pip install wheel
          pip install setuptools
          
      - name: Extracting Tag name...
        id: tag
        run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3)"
      
      - name: Updating the version in setup.py...
        run: >-
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py
      
      - name: Building...
        run: >-
          python setup.py sdist bdist_wheel
          
      - name: Publishing to PyPI...
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
    